-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateGameRequiredArguments =
    { newGame : Api.InputObject.NewGameInput }


{-|

  - newGame -

-}
createGame : CreateGameRequiredArguments -> SelectionSet decodesTo Api.Object.Game -> SelectionSet decodesTo RootMutation
createGame requiredArgs object_ =
    Object.selectionForCompositeField "createGame" [ Argument.required "newGame" requiredArgs.newGame Api.InputObject.encodeNewGameInput ] object_ identity


type alias SaveGameRequiredArguments =
    { game : Api.InputObject.GameInput }


{-|

  - game -

-}
saveGame : SaveGameRequiredArguments -> SelectionSet decodesTo Api.Object.Game -> SelectionSet decodesTo RootMutation
saveGame requiredArgs object_ =
    Object.selectionForCompositeField "saveGame" [ Argument.required "game" requiredArgs.game Api.InputObject.encodeGameInput ] object_ identity


type alias CreateMapRequiredArguments =
    { map : Api.InputObject.MapInput }


{-|

  - map -

-}
createMap : CreateMapRequiredArguments -> SelectionSet decodesTo Api.Object.Map -> SelectionSet decodesTo RootMutation
createMap requiredArgs object_ =
    Object.selectionForCompositeField "createMap" [ Argument.required "map" requiredArgs.map Api.InputObject.encodeMapInput ] object_ identity
