-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Subscription exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias InternetGameRequiredArguments =
    { playerToken : String }


internetGame : InternetGameRequiredArguments -> SelectionSet decodesTo Api.Object.GameWithoutMap -> SelectionSet decodesTo RootSubscription
internetGame requiredArgs object_ =
    Object.selectionForCompositeField "internetGame" [ Argument.required "playerToken" requiredArgs.playerToken Encode.string ] object_ identity


type alias InternetGameOrConfigurationRequiredArguments =
    { playerToken : String }


internetGameOrConfiguration : InternetGameOrConfigurationRequiredArguments -> SelectionSet decodesTo Api.Union.InternetGameOrConfiguration -> SelectionSet decodesTo RootSubscription
internetGameOrConfiguration requiredArgs object_ =
    Object.selectionForCompositeField "internetGameOrConfiguration" [ Argument.required "playerToken" requiredArgs.playerToken Encode.string ] object_ identity
