version: "3"

services:
  server:
    build: .
    environment:
      API_URL: "${API_URL}"
      PGHOST: "${PGHOST}"
      PGDATABASE: "${PGDATABASE}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: fracas
    volumes:
      - fracas-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  fracas-postgres:
