-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type A
    = A


type B
    = B


type Game
    = Game


type Map
    = Map
