-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type CountryTroopCounts
    = CountryTroopCounts


type Game
    = Game


type Map
    = Map


type Player
    = Player


type PlayerTurn
    = PlayerTurn
