-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.InternetGameConfiguration exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Int Api.Object.InternetGameConfiguration
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| -}
players : SelectionSet decodesTo Api.Object.InternetGamePlayerConfiguration -> SelectionSet (List decodesTo) Api.Object.InternetGameConfiguration
players object_ =
    Object.selectionForCompositeField "players" [] object_ (identity >> Decode.list)


{-| -}
mapId : SelectionSet String Api.Object.InternetGameConfiguration
mapId =
    Object.selectionForField "String" "mapId" [] Decode.string


{-| -}
joinToken : SelectionSet String Api.Object.InternetGameConfiguration
joinToken =
    Object.selectionForField "String" "joinToken" [] Decode.string


{-| -}
userPlayerId : SelectionSet Int Api.Object.InternetGameConfiguration
userPlayerId =
    Object.selectionForField "Int" "userPlayerId" [] Decode.int
